argument_specs:
  main:
    options:
      role_artifacts_path:
        type: str
        required: true
        description: Base playbook path for artifacts output, not including the calling role name.
      calling_role_name:
        type: str
        required: true
        description: Name of the role that is calling this role to set its artifacts.
      calling_role_artifacts_inputs:
        type: dict
        required: true
        description: The incoming artifacts to from the calling role.
