---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-admin
  namespace: db-postgres
spec:
  itemPath: "vaults/HomeLab/items/postgres-admin"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: netbox-db-credentials
  namespace: db-postgres
spec:
  itemPath: "vaults/HomeLab/items/netbox-db-credentials"
