---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-synology-delete
  annotations:
    storageclass.kubernetes.io/description: >-
      NFS-backed storage using nfs-subdir-external-provisioner
      with Delete reclaim policy
provisioner: cluster.local/nfs-subdir-external-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
