---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-synology-delete
  annotations:
    storageclass.kubernetes.io/description: >-
      Requires nfs-subdir-external-provisioner
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
