---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclasses/local-path-delete.yml
  - storageclasses/local-path-retain.yml
  - storageclasses/nfs-synology-delete.yml
  - storageclasses/nfs-synology-retain.yml
