---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - onepassworditem-argocd-token.yml
  - onepassworditem-nextdns-api-token.yml
  - onepassworditem-proxmox-api-password.yml
