---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: homepage-proxmox-api-password
  namespace: infra-homepage
spec:
  itemPath: "vaults/HomeLab/items/Coachlight ProxMox Cluster"
