---
paperless_ngx_deploy_kubeconfig: "{{ k3s_kubeconfig_path | default('', true) }}"
paperless_ngx_deploy_context: "{{ k3s_context_name | default('', true) }}"
paperless_ngx_deploy_cluster_name: "{{ k3s_cluster_name | default('', true) }}"
paperless_ngx_deploy_apply_objects: true
paperless_ngx_deploy_manifest_src: argocd/paperless_ngx/paperless_ngx.yml
