---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: netbox-db-credentials
  namespace: infra-netbox
spec:
  itemPath: "vaults/HomeLab/items/netbox-db-credentials"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: netbox-redis-credentials
  namespace: infra-netbox
spec:
  itemPath: "vaults/HomeLab/items/netbox-redis-credentials"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: netbox-django-secret
  namespace: infra-netbox
spec:
  itemPath: "vaults/HomeLab/items/netbox-django-secret"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: netbox-superuser
  namespace: infra-netbox
spec:
  itemPath: "vaults/HomeLab/items/netbox-superuser"
