---
argument_specs:
  main:
    options:
      argocd_homepage_token_server_url:
        type: str
        required: false
      argocd_homepage_token_widget_url:
        type: str
        required: false
      argocd_homepage_token_username:
        type: str
        required: false
      argocd_homepage_token_namespace:
        type: str
        required: false
      argocd_homepage_token_1p_vault_name:
        type: str
        required: false
      argocd_homepage_token_1p_item_name:
        type: str
        required: false
      argocd_homepage_token_cli_install_method:
        type: str
        required: false
      argocd_homepage_token_cli_version:
        type: str
        required: false
      argocd_homepage_token_artifacts_path:
        type: str
        required: false
      argocd_homepage_token_op_service_account_token:
        type: str
        required: false
