---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netbox
  namespace: infra-netbox
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "NetBox"
    gethomepage.dev/description: "IPAM and datacenter infrastructure management"
    gethomepage.dev/group: "Platform"
    gethomepage.dev/icon: "netbox.png"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - netbox.rohu-shark.ts.net
  rules:
    - host: netbox.rohu-shark.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netbox
                port:
                  number: 80
