---
- name: Import Proxmox node add users
  ansible.builtin.import_tasks: users.yml
- name: Import Proxmox node add NFS and local image storage
  ansible.builtin.import_tasks: storage.yml
- name: Import Proxmox module prerequisites
  ansible.builtin.import_tasks: proxmox-module-prereqs.yml
