---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-ngx-homepage
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: webserver
    app.kubernetes.io/managed-by: argocd
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Paperless-NGX"
    gethomepage.dev/description: "Document management and archive"
    gethomepage.dev/group: "Documents"
    gethomepage.dev/icon: "paperless-ngx.png"
spec:
  rules:
    - host: paperless
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless-ngx-webserver
                port:
                  number: 8000
