---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - configmap.yml
  - pvcs.yml
  - gotenberg.yml
  - tika.yml
  - webserver.yml
  - ingress.yml
  - pv-paperless-consume.yml
  # - migrations/job-migrate-paperless-data.yml
  # - migrations/job-migrate-paperless-media.yml
  # - migrations/job-migrate-paperless-export.yml
