---
- name: Detect existing cluster
  ansible.builtin.stat:
    path: /etc/pve/corosync.conf
  register: corosync_cfg
  become: true

- name: Create cluster (primary)
  ansible.builtin.command: >
    pvecm create {{ proxmox_cluster_name }}
  when:
    - inventory_hostname in groups['proxmox_primary']
    - not corosync_cfg.stat.exists
  register: cluster_create
  changed_when: "'already exists' not in cluster_create.stderr"
