---
nfs_provisioner_deploy_argocd_namespace: argocd
nfs_provisioner_deploy_argocd_application_path: >-
  {{ playbook_dir }}/../argocd/nfs_provisioner/nfs_provisioner.yml
nfs_provisioner_deploy_argocd_app_name: nfs-provisioner
nfs_provisioner_deploy_storageclass_paths:
  - "{{ playbook_dir }}/../k8s/storageclasses/nfs-synology-delete.yml"
  - "{{ playbook_dir }}/../k8s/storageclasses/nfs-synology-retain.yml"
  - "{{ playbook_dir }}/../k8s/storageclasses/nfs-static-retain.yml"
nfs_provisioner_deploy_wait_retries: 30
nfs_provisioner_deploy_wait_delay: 10
