---
argument_specs:
  main:
    options:
      proxmox_maintenance_artifacts_path:
        type: str
        required: false
        description: Base path for artifacts output, used by role_artifacts.
      proxmox_maintenance_enable_reboot:
        type: bool
        required: false
        description: Whether the role is allowed to reboot if required.
      proxmox_maintenance_reboot_timeout:
        type: int
        required: false
        description: >-
          Maximum seconds to wait for the machine to reboot and respond.
