argument_specs:
  main:
    options:
      control_host_dependencies_system_packages:
        type: list
        elements: str
        default: []
      control_host_dependencies_pip_packages:
        type: list
        elements: str
        default: []
      control_host_dependencies_pip_executable:
        type: str
        required: false
        description: Pip executable to use (e.g. pip3).
