---
longhorn_deploy_kubeconfig: "{{ k3s_kubeconfig_path | default('', true) }}"
longhorn_deploy_cluster_name: "{{ k3s_cluster_name | default('', true) }}"
longhorn_deploy_context: "{{ k3s_context_name | default('', true) }}"
