---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mosquitto-allow-ingress
  namespace: infra-mqtt
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: app-template
      app.kubernetes.io/instance: mqtt-broker
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: apps-frigate
      ports:
        - protocol: TCP
          port: 1883
