---
onepassword_operator_deploy_kubeconfig: "{{ k3s_kubeconfig_path | default('', true) }}"
onepassword_operator_deploy_cluster_name: "{{ k3s_cluster_name | default('', true) }}"
onepassword_operator_deploy_context: "{{ k3s_context_name | default('', true) }}"
onepassword_operator_deploy_namespace: "infra-1password-operator"
onepassword_operator_deploy_argocd_namespace: "argocd"
onepassword_operator_deploy_app_name: "1password-operator"
onepassword_operator_deploy_project: "coachlight-k3s-infra"
onepassword_operator_deploy_apply_objects: true
onepassword_operator_deploy_helm_repo_url: "https://1password.github.io/connect-helm-charts/"
onepassword_operator_deploy_chart: "connect"
onepassword_operator_deploy_tailscale_hostname: "1password"
onepassword_operator_deploy_tailscale_tags: "tag:k8s,tag:infra-gitops"
onepassword_operator_deploy_tailnet_domain: "rohu-shark.ts.net"
onepassword_operator_deploy_homepage_name: "1Password Connect"
onepassword_operator_deploy_homepage_description: "Secrets backend for 1Password Operator"
onepassword_operator_deploy_homepage_group: "Platform"
onepassword_operator_deploy_homepage_icon: "onepassword.png"
