---
argument_specs:
  main:
    short_description: Install the 1Password CLI
    options:
      op_install_artifacts_path:
        type: str
        required: true
        description: Global base path for artifacts output, not including the role name.
