---
argument_specs:
  main:
    short_description: Validate presence and configuration of the 1Password CLI using a service account token
    options:
      op_validator_artifacts_path:
        type: str
        required: true
        description: >-
          Global base path for artifacts output, not including the role name.
      op_validator_op_executable:
        type: str
        default: op
        description:
          - Path or name of the op CLI executable to validate.
      op_validator_op_account_type:
        type: str
        required: true
        description:
          - The expected 1Password account type to validate against when checking authentication.
      op_validator_op_service_account_token:
        type: str
        required: true
        description:
          - Resolved 1Password service account token to validate.
