all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    desktops:
      hosts:
        sfroeber-amd-fedora-desktop: {}

    laptops:
      hosts:
        sfroeber-amd-fedora-laptop: {}

    proxmox:
      hosts:
        coachlight-homelab-1:
          ansible_host: 192.168.226.90
        coachlight-homelab-2:
          ansible_host: 192.168.226.91
        coachlight-homelab-3:
          ansible_host: 192.168.226.92

    k3s_control_plane:
      hosts:
        k3s-cp-1:
          ansible_host: 192.168.226.93
        k3s-cp-2:
          ansible_host: 192.168.226.94
        k3s-cp-3:
          ansible_host: 192.168.226.95

    k3s_workers:
      hosts:
        k3s-wkr-1:
          ansible_host: 192.168.226.96
        k3s-wkr-2:
          ansible_host: 192.168.226.97
        k3s-media-wkr-3:
          ansible_host: 192.168.226.98

    fedora_vms:
      children:
        k3s_control_plane: {}
        k3s_workers: {}

    # This is the "cluster meta-group"
    k3s_on_proxmox:
      children:
        local: {}
        proxmox: {}
        fedora_vms: {}

    # Everything in your homelab, including random desktops
    coachlight_homelab:
      children:
        k3s_on_proxmox: {}
        desktops: {}
        laptops: {}
