# ansible/inventories/hosts.yml
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    desktops:
      hosts:
        sfroeber-amd-fedora-desktop: {}

    laptops:
      hosts:
        sfroeber-amd-fedora-laptop: {}

    proxmox:
      hosts:
        coachlight-homelab-1:
          lan_ip: 192.168.226.90
        coachlight-homelab-2:
          lan_ip: 192.168.226.91
        coachlight-homelab-3:
          lan_ip: 192.168.226.92

    k3s_control_plane:
      hosts:
        k3s-cp-1:
          lan_ip: 192.168.226.93
        k3s-cp-2:
          lan_ip: 192.168.226.94
        k3s-cp-3:
          lan_ip: 192.168.226.95

    k3s_workers:
      hosts:
        k3s-wkr-1:
          lan_ip: 192.168.226.96
        k3s-wkr-2:
          lan_ip: 192.168.226.97
        k3s-media-wkr-3:
          lan_ip: 192.168.226.98

    k3s_cluster:
      children:
        k3s_control_plane: {}
        k3s_workers: {}

    proxmox_cluster:
      children:
        local: {}
        proxmox: {}
        k3s_cluster: {}

    synology_nas:
      hosts:
        srfaudio:
          lan_ip: 192.168.226.6
          ts_ip: 100.64.218.83

    coachlight_homelab:
      children:
        proxmox_cluster: {}
        desktops: {}
        laptops: {}
