---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: paperless-ngx-redis-secrets
  namespace: apps-paperless-ngx
spec:
  itemPath: "vaults/HomeLab/items/Paperless-NGX Redis Variables"
