---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: paperless-ngx-secrets
  namespace: apps-paperless-ngx
spec:
  itemPath: "vaults/HomeLab/items/Paperless-NGX Server Variables"
