---
argument_specs:
  main:
    options:
      homepage_deploy_kubeconfig:
        type: str
        required: false
      homepage_deploy_cluster_name:
        type: str
        required: false
      homepage_deploy_context:
        type: str
        required: false
      homepage_deploy_namespace:
        type: str
        required: false
      homepage_deploy_argo_namespace:
        type: str
        required: false
      homepage_deploy_project:
        type: str
        required: false
      homepage_deploy_argocd_manifests_path:
        type: str
        required: false
