- name: Setup KDE Activities
  ansible.builtin.command:
    cmd: >-
      qdbus org.kde.ActivityManager /ActivityManager/Activities
      AddActivity "{{ item }}"
  loop:
    - "Work"
    - "Homelab"
  loop_control:
    label: "{{ item }}"
  become: true
  when: ansible_facts['desktop_environment'] == 'KDE'
  tags: kde
