velero_deploy_kubeconfig: "{{ k3s_kubeconfig_path | default('', true) }}"
velero_deploy_context: "{{ k3s_context_name | default('', true) }}"
velero_deploy_cluster_name: "{{ k3s_cluster_name | default('', true) }}"

velero_deploy_namespace: infra-velero
velero_deploy_argo_namespace: argocd
velero_deploy_argo_project: coachlight-k3s-infra

velero_deploy_application_name: velero

velero_deploy_helm_repo_url: https://vmware-tanzu.github.io/helm-charts
velero_deploy_helm_chart_name: velero
velero_deploy_helm_chart_version: "8.7.0"
velero_deploy_csi_plugin_version: "v0.7.1"

velero_deploy_backup_storage_location: default
velero_deploy_backup_storage_config: {}
velero_deploy_snapshot_location_config: {}

velero_deploy_tmp_dir: "{{ artifacts_path | default('/tmp') }}/velero_deploy"
