---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: tailscale-operator-oauth
  namespace: infra-tailscale-operator
spec:
  itemPath: "vaults/homelab-k8s-secrets/items/tailscale-operator-oauth"
