---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: infra-homepage
data:
  services.yaml: |
    - GitOps:
        - Argo CD:
            href: https://argocd.rohu-shark.ts.net
            description: GitOps control plane
            icon: argocd.png
            widget:
              type: argocd
              url: https://argocd.rohu-shark.ts.net
              key: "{{HOMEPAGE_VAR_ARGOCD_TOKEN}}"

    - Monitoring:
        - NextDNS:
            href: https://my.nextdns.io
            widget:
              type: nextdns
              profile: 62778c
              key: "{{HOMEPAGE_VAR_NEXTDNS_TOKEN}}"

        - Proxmox:
            href: https://192.168.226.90:8006
            widget:
              type: proxmox
              url: https://192.168.226.90:8006
              username: sfroeber
              password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"

  widgets.yaml: |
    - datetime:
        format:
          dateStyle: short
          timeStyle: short
          hourCycle: h23

    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

  kubernetes.yaml: |
    mode: cluster

  settings.yaml: |
    {}
