homepage_deploy_namespace: infra-homepage
homepage_deploy_argo_namespace: argocd
homepage_deploy_project: coachlight-k3s-infra

homepage_deploy_chart_repo: https://jameswynn.github.io/helm-charts
homepage_deploy_chart_name: homepage
homepage_deploy_chart_version: 2.1.0

homepage_deploy_application_name: homepage

homepage_deploy_ingress_templates_root: "{{ role_path }}/templates/ingresses"

homepage_deploy_artifacts_path: "{{ artifacts_path }}"

homepage_deploy_proxmox_node_name: pve
homepage_deploy_proxmox_url: ""
homepage_deploy_proxmox_username: ""
homepage_deploy_proxmox_secret: ""
