apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: coachlight-k3s-infra
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: "1.90.8"
    helm:
      valuesObject:
        oauth:
          clientId: "k6YmEhKb4F11CNTRL"
          clientSecret: "tskey-client-k6YmEhKb4F11CNTRL-zkNKd949a9G382rMet1w9GfHdjWmY1uz"
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tailscale-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
