---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crafty-controller
  namespace: apps-crafty-controller
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Crafty Controller"
    gethomepage.dev/group: "Games"
    gethomepage.dev/description: "Minecraft server manager"
    gethomepage.dev/icon: "crafty"
spec:
  ingressClassName: tailscale
  rules:
    - host: crafty-controller.rohu-shark.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crafty-controller
                port:
                  number: 443
  tls:
    - hosts:
        - crafty-controller
