---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - namespace.yml
  - onepassworditem-crafty-default-json.yml
  - pvc-backups.yml
  - pvc-config.yml
  - pvc-import.yml
  - pvc-logs.yml
  - pvc-servers.yml
  - service.yml
