---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: crafty-controller-default-json
  namespace: apps-crafty-controller
spec:
  itemPath: "vaults/HomeLab/items/ovc2tfzndfnajjyxdehrox6lcy"
