---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: crafty-controller-default-json
  namespace: apps-crafty-controller
spec:
  itemPath: "vaults/coachlight-homelab/items/crafty-controller-default-json"
