---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-controller-backups
  namespace: apps-crafty-controller
  labels:
    app: crafty-controller
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-csi-nfs-delete
  resources:
    requests:
      storage: 20Gi
