---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-controller-backups
  namespace: apps-crafty-controller
  labels:
    app: crafty-controller
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-synology-retain
  resources:
    requests:
      storage: 20Gi
