---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate
  namespace: apps-frigate
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Frigate"
    gethomepage.dev/description: "NVR with realtime object detection"
    gethomepage.dev/group: "Cameras"
    gethomepage.dev/icon: "frigate.png"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - frigate.rohu-shark.ts.net
  rules:
    - host: frigate.rohu-shark.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frigate
                port:
                  number: 5000
