---
argument_specs:
  main:
    options:
      op_vault_validator_artifacts_path:
        type: str
        required: true
        description: >-
          Global base path for artifacts output, not including the role name.
      op_vault_validator_vault_name:
        type: str
        required: true
        description: >
          1Password vault name to validate. If the vault does not exist,
          this role will create it.
      op_vault_validator_op_service_account_token:
        type: str
        required: true
        description:
          - 1Password service account token used for op CLI authentication.
