---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: infra-homepage
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Homepage"
    gethomepage.dev/description: "Application dashboard and service discovery"
    gethomepage.dev/group: "Platform"
    gethomepage.dev/icon: "homepage.png"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - homepage.rohu-shark.ts.net
  rules:
    - host: homepage.rohu-shark.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 80
