argument_specs:
  main:
    short_description: Publish arbitrary files from controller to target Proxmox nodes.
    options:
      file_publish_targets:
        type: list
        elements: str
        required: true
      file_publish_items:
        type: list
        elements: dict
        required: true
        options:
          src:
            type: str
            required: true
          dest:
            type: str
            required: true
          mode:
            type: str
            required: false
          owner:
            type: str
            required: false
          group:
            type: str
            required: false
      file_publish_default_mode:
        type: str
        required: false
      file_publish_artifact_path:
        type: str
        required: false
