name: Ansible Site Test

on:
  workflow_dispatch:
  push:
    paths:
      - "ansible/**"
      - "site.yml"
      - ".github/workflows/ansible-site-test.yml"
  pull_request:
    paths:
      - "ansible/**"
      - "site.yml"
      - ".github/workflows/ansible-site-test.yml"

env:
  REGISTRY: ghcr.io

jobs:
  ansible-site-test:
    runs-on: ubuntu-latest
    environment: HomeLab Actions

    permissions:
      contents: read
      packages: read

    steps:
      - name: Normalize repo name to lowercase
        id: normalize
        run: |
          echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set container image path
        id: image
        run: |
          echo "IMAGE=ghcr.io/${{ steps.normalize.outputs.REPO_LOWER }}/fedora-ansible-43-ansible:latest" >> $GITHUB_OUTPUT

      - name: Run playbook inside container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ steps.image.outputs.IMAGE }}
          options: |
            --pull=always
            -e OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          run: |
            pwd
            tree -aC
            cd ansible
            ansible-galaxy collection install -r requirements.yml
            ansible-playbook playbooks/op_tester.yml -vv
