name: Ansible Site Test

on:
  workflow_dispatch:
  push:
    paths:
      - "ansible/**"
      - "site.yml"
      - ".github/workflows/ansible-site-test.yml"
  pull_request:
    paths:
      - "ansible/**"
      - "site.yml"
      - ".github/workflows/ansible-site-test.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_LOWER: ${{ toLower(github.repository) }}

jobs:
  ansible-site-test:
    runs-on: ubuntu-latest
    environment: HomeLab Actions
    permissions:
      contents: read
      packages: read

    container:
      image: ghcr.io/${{ env.IMAGE_NAME_LOWER }}/fedora-ansible-43-ansible:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible Galaxy collections
        working-directory: ansible
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run Ansible playbook
        working-directory: ansible
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: ansible-playbook playbooks/op_tester.yml -vv

      - name: Setup op credentials
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: op user get --me
        shell: bash
